# Generated by Django 5.2 on 2025-04-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(null=True, upload_to='patient_photos/'),
        ),
    ]
