# Generated by Django 5.2 on 2025-04-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
    ]
