# Generated by Django 5.2 on 2025-04-17 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_patient_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('ward', models.CharField(max_length=50)),
                ('bed_number', models.CharField(max_length=20)),
                ('doctor_assigned', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Admitted', max_length=20)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='hospapp.patient')),
            ],
        ),
    ]
