# Generated by Django 5.2 on 2025-04-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_admissionrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdmissionRecord',
            new_name='Admission',
        ),
    ]
